name: grievance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  intl: ^0.17.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  file_picker: ^5.2.0+1
  image_picker: ^0.8.6
  image_cropper: ^3.0.0
  #flutter_slidable: ^1.2.0
  camera: ^0.10.0+3
  video_player: ^2.4.7
  path_provider: ^2.0.11
  permission_handler: ^10.1.0
  flick_video_player: ^0.5.0
  visibility_detector: ^0.3.3
  just_audio: ^0.9.29
  flutter_typeahead: ^4.1.1
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.1
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.1.0
  flutter_login_facebook: ^1.6.0
  shimmer: ^2.0.0
  share: ^2.0.4
  syncfusion_flutter_pdfviewer: ^20.3.48
  pinch_zoom: ^1.0.0
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^13.0.4
  flutter_local_notifications: ^12.0.0
  rxdart: ^0.27.5
  connectivity_plus: ^2.3.8
  country_state_city_picker: ^1.2.8
  url_launcher: ^6.1.6
  pin_code_fields: ^7.4.0
  popover: ^0.2.6+3
  dropdown_button2: ^1.8.5
  image_size_getter: ^2.1.2
  readmore: ^2.2.0
  progress_dialog_null_safe: ^1.0.7
  flowder: ^0.2.0
  android_path_provider: ^0.3.0
  device_info_plus: ^8.0.0
  sticky_grouped_list: ^3.1.0
  #ars_progress_dialog: ^0.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf
        - asset: assets/fonts/montserrat.ttf
          style: italic
    - family: montserrat bold
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
